name: Ash CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
  ash-3-ci:
    uses: ash-project/ash/.github/workflows/ash-3-ci.yml@main
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    env:
      FLAG_ASH_THREE: true
